-- MySQL Script generated by MySQL Workbench
-- 02/13/15 13:16:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CaraLibro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CaraLibro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CaraLibro` ;
USE `CaraLibro` ;

-- -----------------------------------------------------
-- Table `CaraLibro`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`actor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_actor_last_name` ON `CaraLibro`.`actor` (`last_name` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`country` (
  `country_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(50) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CaraLibro`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`city` (
  `city_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(50) NOT NULL,
  `country_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`city_id`),
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `CaraLibro`.`country` (`country_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_country_id` ON `CaraLibro`.`city` (`country_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`address` (
  `address_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(50) NOT NULL,
  `address2` VARCHAR(50) NULL DEFAULT NULL,
  `district` VARCHAR(20) NOT NULL,
  `city_id` SMALLINT UNSIGNED NOT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`address_id`),
  CONSTRAINT `fk_address_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `CaraLibro`.`city` (`city_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_city_id` ON `CaraLibro`.`address` (`city_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`category` (
  `category_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CaraLibro`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`staff` (
  `staff_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address_id` SMALLINT UNSIGNED NOT NULL,
  `picture` BLOB NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `store_id` TINYINT UNSIGNED NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT TRUE,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(40) BINARY NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`staff_id`),
  CONSTRAINT `fk_staff_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `CaraLibro`.`store` (`store_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_staff_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `CaraLibro`.`address` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_store_id` ON `CaraLibro`.`staff` (`store_id` ASC);

CREATE INDEX `idx_fk_address_id` ON `CaraLibro`.`staff` (`address_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`store` (
  `store_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manager_staff_id` TINYINT UNSIGNED NOT NULL,
  `address_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`store_id`),
  CONSTRAINT `fk_store_staff`
    FOREIGN KEY (`manager_staff_id`)
    REFERENCES `CaraLibro`.`staff` (`staff_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_store_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `CaraLibro`.`address` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idx_unique_manager` ON `CaraLibro`.`store` (`manager_staff_id` ASC);

CREATE INDEX `idx_fk_address_id` ON `CaraLibro`.`store` (`address_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`customer` (
  `customer_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_id` TINYINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `address_id` SMALLINT UNSIGNED NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT TRUE,
  `create_date` DATETIME NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `fk_customer_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `CaraLibro`.`address` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `CaraLibro`.`store` (`store_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the addre' /* comment truncated */ /*s table and the store table where this customer is registered.

Basic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.*/;

CREATE INDEX `idx_fk_store_id` ON `CaraLibro`.`customer` (`store_id` ASC);

CREATE INDEX `idx_fk_address_id` ON `CaraLibro`.`customer` (`address_id` ASC);

CREATE INDEX `idx_last_name` ON `CaraLibro`.`customer` (`last_name` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`language` (
  `language_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(20) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CaraLibro`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`film` (
  `film_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `release_year` YEAR NULL,
  `language_id` TINYINT UNSIGNED NOT NULL,
  `original_language_id` TINYINT UNSIGNED NULL DEFAULT NULL,
  `rental_duration` TINYINT UNSIGNED NOT NULL DEFAULT 3,
  `rental_rate` DECIMAL(4,2) NOT NULL DEFAULT 4.99,
  `length` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `replacement_cost` DECIMAL(5,2) NOT NULL DEFAULT 19.99,
  `rating` ENUM('G','PG','PG-13','R','NC-17') NULL DEFAULT 'G',
  `special_features` SET('Trailers','Commentaries','Deleted Scenes','Behind the Scenes') NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`film_id`),
  CONSTRAINT `fk_film_language`
    FOREIGN KEY (`language_id`)
    REFERENCES `CaraLibro`.`language` (`language_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_language_original`
    FOREIGN KEY (`original_language_id`)
    REFERENCES `CaraLibro`.`language` (`language_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_title` ON `CaraLibro`.`film` (`title` ASC);

CREATE INDEX `idx_fk_language_id` ON `CaraLibro`.`film` (`language_id` ASC);

CREATE INDEX `idx_fk_original_language_id` ON `CaraLibro`.`film` (`original_language_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`film_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`film_actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL,
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`actor_id`, `film_id`),
  CONSTRAINT `fk_film_actor_actor`
    FOREIGN KEY (`actor_id`)
    REFERENCES `CaraLibro`.`actor` (`actor_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_actor_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `CaraLibro`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_film_id` ON `CaraLibro`.`film_actor` (`film_id` ASC);

CREATE INDEX `fk_film_actor_actor_idx` ON `CaraLibro`.`film_actor` (`actor_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`film_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`film_category` (
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `category_id` TINYINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`film_id`, `category_id`),
  CONSTRAINT `fk_film_category_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `CaraLibro`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_category_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `CaraLibro`.`category` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_film_category_category_idx` ON `CaraLibro`.`film_category` (`category_id` ASC);

CREATE INDEX `fk_film_category_film_idx` ON `CaraLibro`.`film_category` (`film_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`film_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`film_text` (
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`film_id`))
ENGINE = InnoDB;

CREATE FULLTEXT INDEX `idx_title_description` ON `CaraLibro`.`film_text` (`title` ASC, `description` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`inventory` (
  `inventory_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `store_id` TINYINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`inventory_id`),
  CONSTRAINT `fk_inventory_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `CaraLibro`.`store` (`store_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inventory_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `CaraLibro`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_film_id` ON `CaraLibro`.`inventory` (`film_id` ASC);

CREATE INDEX `idx_store_id_film_id` ON `CaraLibro`.`inventory` (`store_id` ASC, `film_id` ASC);

CREATE INDEX `fk_inventory_store_idx` ON `CaraLibro`.`inventory` (`store_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`rental` (
  `rental_id` INT NOT NULL AUTO_INCREMENT,
  `rental_date` DATETIME NOT NULL,
  `inventory_id` MEDIUMINT UNSIGNED NOT NULL,
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  `return_date` DATETIME NULL,
  `staff_id` TINYINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rental_id`),
  CONSTRAINT `fk_rental_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `CaraLibro`.`staff` (`staff_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rental_inventory`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `CaraLibro`.`inventory` (`inventory_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rental_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `CaraLibro`.`customer` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idx_rental` ON `CaraLibro`.`rental` (`rental_date` ASC, `inventory_id` ASC, `customer_id` ASC);

CREATE INDEX `idx_fk_inventory_id` ON `CaraLibro`.`rental` (`inventory_id` ASC);

CREATE INDEX `idx_fk_customer_id` ON `CaraLibro`.`rental` (`customer_id` ASC);

CREATE INDEX `idx_fk_staff_id` ON `CaraLibro`.`rental` (`staff_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`payment` (
  `payment_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  `staff_id` TINYINT UNSIGNED NOT NULL,
  `rental_id` INT NULL DEFAULT NULL,
  `amount` DECIMAL(5,2) NOT NULL,
  `payment_date` DATETIME NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  CONSTRAINT `fk_payment_rental`
    FOREIGN KEY (`rental_id`)
    REFERENCES `CaraLibro`.`rental` (`rental_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `CaraLibro`.`customer` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `CaraLibro`.`staff` (`staff_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_staff_id` ON `CaraLibro`.`payment` (`staff_id` ASC);

CREATE INDEX `idx_fk_customer_id` ON `CaraLibro`.`payment` (`customer_id` ASC);

CREATE INDEX `fk_payment_rental_idx` ON `CaraLibro`.`payment` (`rental_id` ASC);


-- -----------------------------------------------------
-- Table `CaraLibro`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`user` (
  `username` (16) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `CaraLibro`.`user_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`user_1` (
  `username` (16) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `CaraLibro`.`amities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`amities` (
  `id_amitie` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur_D` INT NOT NULL,
  `id_utilisateur_A` INT NOT NULL,
  PRIMARY KEY (`id_amitie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaraLibro`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`publications` (
  `id_publi` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NOT NULL,
  `heure` TIME NOT NULL,
  `date` DATE NOT NULL,
  `photo` BLOB NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `nbr_like` INT NOT NULL,
  `nbr_com` INT NOT NULL,
  `visibilite` TINYINT(1) NULL,
  PRIMARY KEY (`id_publi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaraLibro`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`messages` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur_E` INT NOT NULL,
  `id_utilisateur_R` INT NOT NULL,
  `heure` TIME NOT NULL,
  `date` DATE NOT NULL,
  `message` VARCHAR(1000) NOT NULL,
  `lu` TINYINT(1) NULL,
  `visibilite_E` TINYINT(1) NULL,
  `visibilite_R` TINYINT(1) NULL,
  PRIMARY KEY (`id_message`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaraLibro`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`likes` (
  `id_com_publi` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NOT NULL,
  `type` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_com_publi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaraLibro`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`commentaires` (
  `id_com` INT NOT NULL,
  `id_publi` INT NOT NULL,
  `id_utilisateur` INT NOT NULL,
  `heure` TIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date` DATE NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `nbr_like` INT NULL,
  `visibilite` TINYINT(1) NULL,
  PRIMARY KEY (`id_com`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaraLibro`.`signalements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`signalements` (
  `id_com_publi` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NOT NULL,
  `heure` TIME NOT NULL,
  `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_com_publi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaraLibro`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaraLibro`.`utilisateurs` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(50) NOT NULL,
  `mdp` VARCHAR(10) NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  `age` INT NOT NULL,
  `sexe` CHAR(1) NOT NULL,
  `photo` BLOB NOT NULL,
  `connecte` TINYINT(1) NULL,
  `supprime` TINYINT(1) NULL,
  `bloque` TINYINT(1) NULL,
  `publications_id_publi` INT NOT NULL,
  `amities_id_amitie` INT NOT NULL,
  `amities_id_utilisateur_D` INT NOT NULL,
  `amities_id_utilisateur_A` INT NOT NULL,
  `messages_id_message` INT NOT NULL,
  `likes_id_com_publi` INT NOT NULL,
  `commentaires_id_com` INT NOT NULL,
  `signalements_id_com_publi` INT NOT NULL,
  PRIMARY KEY (`id_utilisateur`, `publications_id_publi`, `amities_id_amitie`, `amities_id_utilisateur_D`, `amities_id_utilisateur_A`, `messages_id_message`, `likes_id_com_publi`, `commentaires_id_com`, `signalements_id_com_publi`),
  CONSTRAINT `fk_utilisateurs_publications1`
    FOREIGN KEY (`publications_id_publi`)
    REFERENCES `CaraLibro`.`publications` (`id_publi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateurs_amities1`
    FOREIGN KEY (`amities_id_amitie` , `amities_id_utilisateur_D` , `amities_id_utilisateur_A`)
    REFERENCES `CaraLibro`.`amities` (`id_amitie` , `id_utilisateur_D` , `id_utilisateur_A`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateurs_messages1`
    FOREIGN KEY (`messages_id_message`)
    REFERENCES `CaraLibro`.`messages` (`id_message`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateurs_likes1`
    FOREIGN KEY (`likes_id_com_publi`)
    REFERENCES `CaraLibro`.`likes` (`id_com_publi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateurs_commentaires1`
    FOREIGN KEY (`commentaires_id_com`)
    REFERENCES `CaraLibro`.`commentaires` (`id_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateurs_signalements1`
    FOREIGN KEY (`signalements_id_com_publi`)
    REFERENCES `CaraLibro`.`signalements` (`id_com_publi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_utilisateurs_publications1_idx` ON `CaraLibro`.`utilisateurs` (`publications_id_publi` ASC);

CREATE INDEX `fk_utilisateurs_amities1_idx` ON `CaraLibro`.`utilisateurs` (`amities_id_amitie` ASC, `amities_id_utilisateur_D` ASC, `amities_id_utilisateur_A` ASC);

CREATE INDEX `fk_utilisateurs_messages1_idx` ON `CaraLibro`.`utilisateurs` (`messages_id_message` ASC);

CREATE INDEX `fk_utilisateurs_likes1_idx` ON `CaraLibro`.`utilisateurs` (`likes_id_com_publi` ASC);

CREATE INDEX `fk_utilisateurs_commentaires1_idx` ON `CaraLibro`.`utilisateurs` (`commentaires_id_com` ASC);

CREATE INDEX `fk_utilisateurs_signalements1_idx` ON `CaraLibro`.`utilisateurs` (`signalements_id_com_publi` ASC);

USE `CaraLibro`;

DELIMITER $$
USE `CaraLibro`$$

CREATE TRIGGER `ins_film` AFTER INSERT ON `film` FOR EACH ROW BEGIN
    INSERT INTO film_text (film_id, title, description)
        VALUES (new.film_id, new.title, new.description);
  END$$

USE `CaraLibro`$$

CREATE TRIGGER `upd_film` AFTER UPDATE ON `film` FOR EACH ROW BEGIN
    IF (old.title != new.title) or (old.description != new.description)
    THEN
        UPDATE film_text
            SET title=new.title,
                description=new.description,
                film_id=new.film_id
        WHERE film_id=old.film_id;
    END IF;
  END$$

USE `CaraLibro`$$

CREATE TRIGGER `del_film` AFTER DELETE ON `film` FOR EACH ROW BEGIN
    DELETE FROM film_text WHERE film_id = old.film_id;
  END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
